@startuml
'https://plantuml.com/class-diagram

class HelpScreenController {
-Stage stage
-Scene scene
-Parent root
+Label welcomeText
+Button returnButton
+continueToTaskListScreen(ActionEvent actionEvent)
}

@enduml